
package sol_y_luna.utp.edu.pe.view;

import java.awt.Color;
import javax.swing.JOptionPane;
import sol_y_luna.utp.edu.pe.model.dao.UsuarioDao;

import sol_y_luna.utp.edu.pe.model.dto.Usuario;


public class AccesoView extends javax.swing.JFrame {

    /**
     * Creates new form frmAcceso
     */
    public AccesoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPrincipal = new javax.swing.JPanel();
        bgTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        separator1 = new javax.swing.JSeparator();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        separator2 = new javax.swing.JSeparator();
        btnIngresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));

        bgPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        bgPrincipal.setPreferredSize(new java.awt.Dimension(600, 500));
        bgPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgTitulo.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("HOTEL SOL Y LUNA");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hotel.png"))); // NOI18N

        javax.swing.GroupLayout bgTituloLayout = new javax.swing.GroupLayout(bgTitulo);
        bgTitulo.setLayout(bgTituloLayout);
        bgTituloLayout.setHorizontalGroup(
            bgTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgTituloLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(117, 117, 117))
        );
        bgTituloLayout.setVerticalGroup(
            bgTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgTituloLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(69, 69, 69))
        );

        bgPrincipal.add(bgTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 170));

        lblUsuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblUsuario.setText("USUARIO");
        bgPrincipal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("Ingrese su usuario aqui");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        bgPrincipal.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 360, 30));
        bgPrincipal.add(separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 370, 20));

        lblContrasena.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblContrasena.setText("CONTRASEÑA");
        bgPrincipal.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        txtContrasena.setForeground(new java.awt.Color(153, 153, 153));
        txtContrasena.setText("123456789");
        txtContrasena.setBorder(null);
        txtContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContrasenaMouseClicked(evt);
            }
        });
        bgPrincipal.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 360, 30));
        bgPrincipal.add(separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 370, 10));

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/login.png"))); // NOI18N
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });
        bgPrincipal.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        validarUsuario();
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        if (txtUsuario.getText().equals("Ingrese su usuario aqui")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.BLACK);
        }

        if (String.valueOf(txtContrasena.getPassword()).isEmpty()) {
            txtContrasena.setText("123456789");
            txtContrasena.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void txtContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContrasenaMouseClicked
        if (String.valueOf(txtContrasena.getPassword()).equals("123456789")) {
            txtContrasena.setText("");
            txtContrasena.setForeground(Color.BLACK);
        }

        if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setText("Ingrese su usuario aqui");
            txtUsuario.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtContrasenaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesoView().setVisible(true);
            }
        });
    }

    private int intentosFallidos = 0; // Variable para contar intentos fallidos

    private void validarUsuario() {
        Usuario objUsuario = new Usuario();
        UsuarioDao usuarioDatos = new UsuarioDao();

        objUsuario.setUsuario(txtUsuario.getText());
        objUsuario.setPassword(String.valueOf(txtContrasena.getPassword()));
        objUsuario = usuarioDatos.validarUsuario(objUsuario);

        if (objUsuario != null) {
            JOptionPane.showMessageDialog(this, "BIENVENIDO");
            PrincipalView frmPrincipal = new PrincipalView();
            frmPrincipal.setVisible(true);
            this.dispose();
        } else {
            intentosFallidos++;
            if (intentosFallidos >= 3) {
                JOptionPane.showMessageDialog(this, "Acceso denegado. Se cerrará la aplicación.");
                System.exit(0); // Cierra la aplicación
            } else {
                JOptionPane.showMessageDialog(this, "ACCESO DENEGADO. Intento fallido número " + intentosFallidos);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPrincipal;
    private javax.swing.JPanel bgTitulo;
    private javax.swing.JLabel btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
