
package sol_y_luna.utp.edu.pe.view;

import sol_y_luna.utp.edu.pe.controller.CaracteristicaController;
import sol_y_luna.utp.edu.pe.model.dto.CaracteristicaServicio;

import java.util.List;


public class PopUpServiciosView extends javax.swing.JPanel {

    /**
     * Creates new form PopUpServiciosView
     */
    public PopUpServiciosView(Integer numHabitacion) {
        initComponents();
        txtNroHabitacion_Servicios.setText(String.valueOf(numHabitacion));
        
        CaracteristicaController caracteristicaController = new CaracteristicaController();
        List<CaracteristicaServicio> servicios = caracteristicaController.buscarHabitacion(numHabitacion);
        
        for(CaracteristicaServicio servicio : servicios) {
            switch (servicio.getNombreServicio()) {
                case "JACUZZI":
                    checkJacuzzi.setSelected(true);
                    break;
                case "TELEVISION":
                    checkTV.setSelected(true);
                    break;
                case "AGUA CALIENTE":
                    checkAguaCaliente.setSelected(true);
                    break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Servicios = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNroHabitacion_Servicios = new javax.swing.JLabel();
        txtNroHabitacion_Servicios = new javax.swing.JTextField();
        checkAguaCaliente = new javax.swing.JCheckBox();
        checkJacuzzi = new javax.swing.JCheckBox();
        checkTV = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(680, 300));
        setMinimumSize(new java.awt.Dimension(680, 300));
        setPreferredSize(new java.awt.Dimension(680, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Servicios.setBackground(new java.awt.Color(127, 178, 229));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("SERVICIOS");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Puede ver los servicios asociados a esta habitación");

        javax.swing.GroupLayout ServiciosLayout = new javax.swing.GroupLayout(Servicios);
        Servicios.setLayout(ServiciosLayout);
        ServiciosLayout.setHorizontalGroup(
            ServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiciosLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(20, 20, 20))
        );
        ServiciosLayout.setVerticalGroup(
            ServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiciosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(ServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(ServiciosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9)))
                .addGap(17, 17, 17))
        );

        add(Servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        lblNroHabitacion_Servicios.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lblNroHabitacion_Servicios.setText("NRO HABITACIÓN");
        add(lblNroHabitacion_Servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));
        add(txtNroHabitacion_Servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 220, 30));

        checkAguaCaliente.setText("AGUA CALIENTE");
        add(checkAguaCaliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 160, 30));

        checkJacuzzi.setText("JACUZZI");
        add(checkJacuzzi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 110, 30));

        checkTV.setText("TELEVISION");
        add(checkTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 110, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Servicios;
    private javax.swing.JCheckBox checkAguaCaliente;
    private javax.swing.JCheckBox checkJacuzzi;
    private javax.swing.JCheckBox checkTV;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblNroHabitacion_Servicios;
    private javax.swing.JTextField txtNroHabitacion_Servicios;
    // End of variables declaration//GEN-END:variables
}
