
package sol_y_luna.utp.edu.pe.view;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.DEFAULT_OPTION;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import sol_y_luna.utp.edu.pe.controller.ClienteController;
import sol_y_luna.utp.edu.pe.controller.HabitacionController;
import sol_y_luna.utp.edu.pe.controller.VisitaController;
import sol_y_luna.utp.edu.pe.model.dto.Cliente;
import sol_y_luna.utp.edu.pe.model.dto.Habitacion;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import sol_y_luna.utp.edu.pe.model.dto.Visita;
import sol_y_luna.utp.edu.pe.model.dto.VisitaEnCurso;


public class PrincipalView extends javax.swing.JFrame {

    DefaultTableModel tablaClientes = new DefaultTableModel();
    DefaultTableModel tablaHabitaciones = new DefaultTableModel();
    DefaultTableModel tablaVisitas = new DefaultTableModel();
    DefaultTableModel tablaMantenimiento = new DefaultTableModel();
    static final String MENSAJE_EXITO = "LA OPERACION SE REALIZÓ CORRECTAMENTE";
    static final String MENSAJE_CLIENTE_NO_EXISTE = "EL CLIENTE NO EXISTE, DEBE REGISTRARLO PRIMERO";
    static final String MENSAJE_HABITACION_EN_USO = "LA HABITACIÓN YA ESTÁ EN USO";
    static final String MENSAJE_ERROR_ESTADO_HABITACION = "VERIFICAR EL ESTADO DE LA HABITACION";
    static final String MENSAJE_ERROR_FALTA_REPORTE = "DEBE SELECCIONAR UN REPORTE";

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        setModeloCliente();
        setModeloHabitacion();
        setModeloVisita();
        setModeloMantenimiento();
        this.setLocationRelativeTo(null);
        this.setTitle("SISTEMA DE HOTELES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHabitaciones = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNum_Habitacion = new javax.swing.JTextField();
        txtNumCamas_Habitacion = new javax.swing.JTextField();
        txtPiso_Habitacion = new javax.swing.JTextField();
        txtPrecio_Habitacion = new javax.swing.JTextField();
        btnActualizar_Habitacion = new javax.swing.JButton();
        btnRegistrar_Habitacion = new javax.swing.JButton();
        cboEstado_Habitacion = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        btnVer_Habitacion = new javax.swing.JButton();
        jScrollPane_Habitacion = new javax.swing.JScrollPane();
        tbjVer_Habitacion = new javax.swing.JTable();
        btnServicios_Habitacion = new javax.swing.JButton();
        btnAlquilar_Habitacion = new javax.swing.JButton();
        jPanelRegistro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNumHabitacion_Visita = new javax.swing.JTextField();
        btnUsarHabitacion = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        txtNumDocumentoCliente_Visita = new javax.swing.JTextField();
        btnValidarCliente = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        btnVer_Visita = new javax.swing.JButton();
        jScrollPane_Visita = new javax.swing.JScrollPane();
        tbjVer_Visita = new javax.swing.JTable();
        jPanelCliente = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtNroDocumento_Cliente = new javax.swing.JTextField();
        txtApellido_Cliente = new javax.swing.JTextField();
        txtNombre_Cliente = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtTelefono_Cliente = new javax.swing.JTextField();
        txtCorreo_Cliente = new javax.swing.JTextField();
        btnRegistrar_Ciente = new javax.swing.JButton();
        btnActualizar_Cliente = new javax.swing.JButton();
        btnVer_Cliente = new javax.swing.JButton();
        cboTipoDocumento_Cliente = new javax.swing.JComboBox<>();
        jScrollPane_Cliente = new javax.swing.JScrollPane();
        tbjVer_Cliente = new javax.swing.JTable();
        lblId_Cliente = new javax.swing.JLabel();
        jPanelMantenimiento = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNumHabitacion_Mantenimiento = new javax.swing.JTextField();
        btnLimpiar_Mantenimiento = new javax.swing.JButton();
        btnDisponibilizar_Mantenimiento = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnVer_Mantenimiento = new javax.swing.JButton();
        jScrollPane_Mantenimiento = new javax.swing.JScrollPane();
        tbjVer_Mantenimiento = new javax.swing.JTable();
        idVisita_Mantenimiento = new javax.swing.JLabel();
        btnBuscarHab_Mantenimiento = new javax.swing.JButton();
        jPanelReportes = new javax.swing.JPanel();
        checkReporteHabMasUsadas = new javax.swing.JRadioButton();
        checkReporteImporteDiario = new javax.swing.JRadioButton();
        checkReporteImporteMensual = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnVerReporte = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        cboMes_Reporte = new javax.swing.JComboBox<>();
        jScrollPane_Reporte = new javax.swing.JScrollPane();
        txtArea_Reporte = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanelHabitaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(127, 178, 229));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("HABITACIONES");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Puede consultar, registrar o actualizar los siguientes datos....");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(22, 22, 22))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addComponent(jLabel8))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelHabitaciones.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel10.setText("Nº HABITACION:");
        jPanelHabitaciones.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel11.setText("Nº CAMAS:");
        jPanelHabitaciones.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel12.setText("PISO:");
        jPanelHabitaciones.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel13.setText("PRECIO:");
        jPanelHabitaciones.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel14.setText("ESTADO:");
        jPanelHabitaciones.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        txtNum_Habitacion.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jPanelHabitaciones.add(txtNum_Habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 220, 30));

        txtNumCamas_Habitacion.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jPanelHabitaciones.add(txtNumCamas_Habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 220, 30));

        txtPiso_Habitacion.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jPanelHabitaciones.add(txtPiso_Habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 220, 30));

        txtPrecio_Habitacion.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jPanelHabitaciones.add(txtPrecio_Habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 220, 30));

        btnActualizar_Habitacion.setBackground(new java.awt.Color(127, 178, 229));
        btnActualizar_Habitacion.setForeground(new java.awt.Color(0, 51, 102));
        btnActualizar_Habitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/loop.png"))); // NOI18N
        btnActualizar_Habitacion.setText("ACTUALIZAR");
        btnActualizar_Habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar_HabitacionActionPerformed(evt);
            }
        });
        jPanelHabitaciones.add(btnActualizar_Habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 130, 30));

        btnRegistrar_Habitacion.setBackground(new java.awt.Color(127, 178, 229));
        btnRegistrar_Habitacion.setForeground(new java.awt.Color(0, 51, 102));
        btnRegistrar_Habitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/diskette.png"))); // NOI18N
        btnRegistrar_Habitacion.setText("REGISTRAR");
        btnRegistrar_Habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar_HabitacionActionPerformed(evt);
            }
        });
        jPanelHabitaciones.add(btnRegistrar_Habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 130, 30));

        cboEstado_Habitacion.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        cboEstado_Habitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccionar---", "DISPONIBLE", "EN USO", "LIMPIEZA" }));
        jPanelHabitaciones.add(cboEstado_Habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 220, 30));
        jPanelHabitaciones.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 750, -1));

        btnVer_Habitacion.setBackground(new java.awt.Color(127, 178, 229));
        btnVer_Habitacion.setForeground(new java.awt.Color(0, 51, 102));
        btnVer_Habitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/see.png"))); // NOI18N
        btnVer_Habitacion.setText("VER");
        btnVer_Habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer_HabitacionActionPerformed(evt);
            }
        });
        jPanelHabitaciones.add(btnVer_Habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 130, 30));

        tbjVer_Habitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbjVer_Habitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbjVer_HabitacionMouseClicked(evt);
            }
        });
        jScrollPane_Habitacion.setViewportView(tbjVer_Habitacion);

        jPanelHabitaciones.add(jScrollPane_Habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 327, 750, 320));

        btnServicios_Habitacion.setBackground(new java.awt.Color(127, 178, 229));
        btnServicios_Habitacion.setForeground(new java.awt.Color(0, 51, 102));
        btnServicios_Habitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/see.png"))); // NOI18N
        btnServicios_Habitacion.setText("SERVICIOS");
        btnServicios_Habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicios_HabitacionActionPerformed(evt);
            }
        });
        jPanelHabitaciones.add(btnServicios_Habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 130, 30));

        btnAlquilar_Habitacion.setBackground(new java.awt.Color(0, 153, 153));
        btnAlquilar_Habitacion.setForeground(new java.awt.Color(0, 51, 102));
        btnAlquilar_Habitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/clave.png"))); // NOI18N
        btnAlquilar_Habitacion.setText("ALQUILAR");
        btnAlquilar_Habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquilar_HabitacionActionPerformed(evt);
            }
        });
        jPanelHabitaciones.add(btnAlquilar_Habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 130, 30));

        jTabbedPane1.addTab("Habitaciones", jPanelHabitaciones);

        jPanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(127, 178, 229));

        jLabel15.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 102));
        jLabel15.setText("REGISTRO DE VISITA");

        jLabel16.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 102));
        jLabel16.setText("Registrará la visita de un cliente");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/recepcion.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelRegistro.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        txtNumHabitacion_Visita.setEditable(false);
        txtNumHabitacion_Visita.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jPanelRegistro.add(txtNumHabitacion_Visita, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 220, 30));

        btnUsarHabitacion.setBackground(new java.awt.Color(127, 178, 229));
        btnUsarHabitacion.setForeground(new java.awt.Color(0, 51, 102));
        btnUsarHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/replace.png"))); // NOI18N
        btnUsarHabitacion.setText("REGISTRAR");
        btnUsarHabitacion.setEnabled(false);
        btnUsarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsarHabitacionActionPerformed(evt);
            }
        });
        jPanelRegistro.add(btnUsarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 130, 30));
        jPanelRegistro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 760, 10));

        jLabel34.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel34.setText("Nº HABITACION:");
        jPanelRegistro.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtNumDocumentoCliente_Visita.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jPanelRegistro.add(txtNumDocumentoCliente_Visita, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 220, 30));

        btnValidarCliente.setBackground(new java.awt.Color(127, 178, 229));
        btnValidarCliente.setForeground(new java.awt.Color(0, 51, 102));
        btnValidarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/validar.png"))); // NOI18N
        btnValidarCliente.setText("VALIDAR");
        btnValidarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarClienteActionPerformed(evt);
            }
        });
        jPanelRegistro.add(btnValidarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 130, 30));

        jLabel35.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel35.setText("DOCUMENTO:");
        jPanelRegistro.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        btnVer_Visita.setBackground(new java.awt.Color(127, 178, 229));
        btnVer_Visita.setForeground(new java.awt.Color(0, 51, 102));
        btnVer_Visita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/see.png"))); // NOI18N
        btnVer_Visita.setText("VER VISITAS");
        btnVer_Visita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer_VisitaActionPerformed(evt);
            }
        });
        jPanelRegistro.add(btnVer_Visita, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 130, 30));

        tbjVer_Visita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbjVer_Visita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbjVer_VisitaMouseClicked(evt);
            }
        });
        jScrollPane_Visita.setViewportView(tbjVer_Visita);

        jPanelRegistro.add(jScrollPane_Visita, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 257, 750, 390));

        jTabbedPane1.addTab("Registro", jPanelRegistro);

        jPanelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(127, 178, 229));

        jLabel26.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 102));
        jLabel26.setText("REGISTRO DE CLIENTE");

        jLabel27.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 51, 102));
        jLabel27.setText("Puede consultar, registrar o actualizar los siguientes datos....");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26))
                .addContainerGap(377, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanelCliente.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));
        jPanelCliente.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 750, 10));

        jLabel28.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel28.setText("APELLIDO:");
        jPanelCliente.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jLabel29.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel29.setText("NRO DOCUMENTO:");
        jPanelCliente.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel30.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel30.setText("TIPO DOCUMENTO:");
        jPanelCliente.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel31.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel31.setText("CORREO:");
        jPanelCliente.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));
        jPanelCliente.add(txtNroDocumento_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 220, 30));
        jPanelCliente.add(txtApellido_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 220, 30));
        jPanelCliente.add(txtNombre_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 220, 30));

        jLabel32.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel32.setText("NOMBRE:");
        jPanelCliente.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel33.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel33.setText("TELEFONO:");
        jPanelCliente.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));
        jPanelCliente.add(txtTelefono_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 220, 30));
        jPanelCliente.add(txtCorreo_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 220, 30));

        btnRegistrar_Ciente.setBackground(new java.awt.Color(127, 178, 229));
        btnRegistrar_Ciente.setForeground(new java.awt.Color(0, 51, 102));
        btnRegistrar_Ciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/diskette.png"))); // NOI18N
        btnRegistrar_Ciente.setText("REGISTRAR");
        btnRegistrar_Ciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar_CienteActionPerformed(evt);
            }
        });
        jPanelCliente.add(btnRegistrar_Ciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 130, 30));

        btnActualizar_Cliente.setBackground(new java.awt.Color(127, 178, 229));
        btnActualizar_Cliente.setForeground(new java.awt.Color(0, 51, 102));
        btnActualizar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/loop.png"))); // NOI18N
        btnActualizar_Cliente.setText("ACTUALIZAR");
        btnActualizar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar_ClienteActionPerformed(evt);
            }
        });
        jPanelCliente.add(btnActualizar_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 130, 30));

        btnVer_Cliente.setBackground(new java.awt.Color(127, 178, 229));
        btnVer_Cliente.setForeground(new java.awt.Color(0, 51, 102));
        btnVer_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/see.png"))); // NOI18N
        btnVer_Cliente.setText("VER");
        btnVer_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer_ClienteActionPerformed(evt);
            }
        });
        jPanelCliente.add(btnVer_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 130, 30));

        cboTipoDocumento_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Seleccionar----", "DNI", "CE" }));
        jPanelCliente.add(cboTipoDocumento_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 220, 30));

        tbjVer_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbjVer_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbjVer_ClienteMouseClicked(evt);
            }
        });
        jScrollPane_Cliente.setViewportView(tbjVer_Cliente);

        jPanelCliente.add(jScrollPane_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 357, 750, 290));

        lblId_Cliente.setText("ID");
        jPanelCliente.add(lblId_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jTabbedPane1.addTab("Cliente", jPanelCliente);

        jPanelMantenimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(127, 178, 229));

        jLabel19.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 102));
        jLabel19.setText("MANTENIMIENTO");

        jLabel20.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 102));
        jLabel20.setText("Limpieza y disponibilización de habitaciones....");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/carro-de-limpieza.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelMantenimiento.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        jLabel22.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel22.setText("Nº HABITACION:");
        jPanelMantenimiento.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txtNumHabitacion_Mantenimiento.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jPanelMantenimiento.add(txtNumHabitacion_Mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 220, 30));

        btnLimpiar_Mantenimiento.setBackground(new java.awt.Color(127, 178, 229));
        btnLimpiar_Mantenimiento.setForeground(new java.awt.Color(0, 51, 102));
        btnLimpiar_Mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/barriendo.png"))); // NOI18N
        btnLimpiar_Mantenimiento.setText("LIMPIAR");
        btnLimpiar_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar_MantenimientoActionPerformed(evt);
            }
        });
        jPanelMantenimiento.add(btnLimpiar_Mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 150, 30));

        btnDisponibilizar_Mantenimiento.setBackground(new java.awt.Color(127, 178, 229));
        btnDisponibilizar_Mantenimiento.setForeground(new java.awt.Color(0, 51, 102));
        btnDisponibilizar_Mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/camas.png"))); // NOI18N
        btnDisponibilizar_Mantenimiento.setText("DISPONIBILIZAR");
        btnDisponibilizar_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisponibilizar_MantenimientoActionPerformed(evt);
            }
        });
        jPanelMantenimiento.add(btnDisponibilizar_Mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 150, 30));
        jPanelMantenimiento.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 750, -1));

        btnVer_Mantenimiento.setBackground(new java.awt.Color(127, 178, 229));
        btnVer_Mantenimiento.setForeground(new java.awt.Color(0, 51, 102));
        btnVer_Mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/see.png"))); // NOI18N
        btnVer_Mantenimiento.setText("VER VISITAS");
        btnVer_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer_MantenimientoActionPerformed(evt);
            }
        });
        jPanelMantenimiento.add(btnVer_Mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 130, 30));

        tbjVer_Mantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbjVer_Mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbjVer_MantenimientoMouseClicked(evt);
            }
        });
        jScrollPane_Mantenimiento.setViewportView(tbjVer_Mantenimiento);

        jPanelMantenimiento.add(jScrollPane_Mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 257, 750, 390));

        idVisita_Mantenimiento.setText("ID VISITA");
        jPanelMantenimiento.add(idVisita_Mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, -1));

        btnBuscarHab_Mantenimiento.setBackground(new java.awt.Color(127, 178, 229));
        btnBuscarHab_Mantenimiento.setForeground(new java.awt.Color(0, 51, 102));
        btnBuscarHab_Mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/validar.png"))); // NOI18N
        btnBuscarHab_Mantenimiento.setText("BUSCAR");
        btnBuscarHab_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHab_MantenimientoActionPerformed(evt);
            }
        });
        jPanelMantenimiento.add(btnBuscarHab_Mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 130, 30));

        jTabbedPane1.addTab("Mantenimiento", jPanelMantenimiento);

        jPanelReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkReporteHabMasUsadas.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        checkReporteHabMasUsadas.setForeground(new java.awt.Color(0, 51, 102));
        checkReporteHabMasUsadas.setText("Habitaciones mas usadas");
        checkReporteHabMasUsadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkReporteHabMasUsadasActionPerformed(evt);
            }
        });
        jPanelReportes.add(checkReporteHabMasUsadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        checkReporteImporteDiario.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        checkReporteImporteDiario.setForeground(new java.awt.Color(0, 51, 102));
        checkReporteImporteDiario.setText("Importe caja diaria");
        checkReporteImporteDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkReporteImporteDiarioActionPerformed(evt);
            }
        });
        jPanelReportes.add(checkReporteImporteDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        checkReporteImporteMensual.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        checkReporteImporteMensual.setForeground(new java.awt.Color(0, 51, 102));
        checkReporteImporteMensual.setText("Importe caja mensual");
        checkReporteImporteMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkReporteImporteMensualActionPerformed(evt);
            }
        });
        jPanelReportes.add(checkReporteImporteMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jPanel3.setBackground(new java.awt.Color(127, 178, 229));

        jLabel23.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 102));
        jLabel23.setText("REPORTES");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/informe.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 102));
        jLabel25.setText("Generación de reportes....");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 509, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelReportes.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        btnVerReporte.setBackground(new java.awt.Color(127, 178, 229));
        btnVerReporte.setForeground(new java.awt.Color(0, 51, 102));
        btnVerReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/see.png"))); // NOI18N
        btnVerReporte.setText("VER REPORTE");
        btnVerReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReporteActionPerformed(evt);
            }
        });
        jPanelReportes.add(btnVerReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 150, 30));
        jPanelReportes.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 760, -1));

        cboMes_Reporte.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        cboMes_Reporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccionar---", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SETIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        jPanelReportes.add(cboMes_Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 220, 30));

        txtArea_Reporte.setColumns(20);
        txtArea_Reporte.setRows(5);
        jScrollPane_Reporte.setViewportView(txtArea_Reporte);

        jPanelReportes.add(jScrollPane_Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 760, 380));

        jTabbedPane1.addTab("Reportes", jPanelReportes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnRegistrar_HabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar_HabitacionActionPerformed
        // TODO add your handling code here:                
        int numHabitacion, numCamas, piso;
        double precio;
        String estado, mensaje;

        numHabitacion = Integer.parseInt(txtNum_Habitacion.getText());
        numCamas = Integer.parseInt(txtNumCamas_Habitacion.getText());
        piso = Integer.parseInt(txtPiso_Habitacion.getText());
        precio = Double.parseDouble(txtPrecio_Habitacion.getText());
        estado = cboEstado_Habitacion.getSelectedItem().toString();
        Habitacion objHabitacion = new Habitacion(numHabitacion, numCamas, piso, precio, estado);

        HabitacionController habitacionController = new HabitacionController();
        mensaje = habitacionController.registrarHabitacion(objHabitacion);

        JOptionPane.showMessageDialog(this, mensaje, "AVISO", INFORMATION_MESSAGE);
        cargarHabitacion();
        limpiarHabitaciones();
    }//GEN-LAST:event_btnRegistrar_HabitacionActionPerformed

    private void btnActualizar_HabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar_HabitacionActionPerformed
        // TODO add your handling code here:
        int numHabitacion, numCamas, piso;
        double precio;
        String estado, mensaje;

        numHabitacion = Integer.parseInt(txtNum_Habitacion.getText());
        numCamas = Integer.parseInt(txtNumCamas_Habitacion.getText());
        piso = Integer.parseInt(txtPiso_Habitacion.getText());
        precio = Double.parseDouble(txtPrecio_Habitacion.getText());
        estado = cboEstado_Habitacion.getSelectedItem().toString();
        Habitacion objHabitacion = new Habitacion(numHabitacion, numCamas, piso, precio, estado);

        HabitacionController habitacionController = new HabitacionController();
        mensaje = habitacionController.actualizarHabitacion(objHabitacion);

        JOptionPane.showMessageDialog(this, mensaje, "AVISO", INFORMATION_MESSAGE);
        cargarHabitacion();
        limpiarHabitaciones();

    }//GEN-LAST:event_btnActualizar_HabitacionActionPerformed

    private void btnUsarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsarHabitacionActionPerformed
        // TODO add your handling code here:
        registrarVisita();
    }//GEN-LAST:event_btnUsarHabitacionActionPerformed

    private void registrarVisita() {
        Integer numHabitacion = Integer.valueOf(txtNumHabitacion_Visita.getText());

        HabitacionController habitacionController = new HabitacionController();
        boolean resultado = habitacionController.usarHabitacion(numHabitacion);

        if (!resultado) {
            JOptionPane.showMessageDialog(this, MENSAJE_HABITACION_EN_USO, "AVISO", DEFAULT_OPTION);
            return;
        }

        ClienteController objClienteController = new ClienteController();
        Cliente objCliente = objClienteController.buscarCliente(txtNumDocumentoCliente_Visita.getText());

        if (objCliente == null) {
            JOptionPane.showMessageDialog(this, MENSAJE_CLIENTE_NO_EXISTE, "AVISO", DEFAULT_OPTION);
            btnUsarHabitacion.setEnabled(false);
            return;
        }

        Visita objVisita = new Visita();
        objVisita.setNroHabitacion(numHabitacion);
        objVisita.setIdCliente(objCliente.getId());

        VisitaController visitaController = new VisitaController();
        String mensaje = visitaController.insertarVisita(objVisita);

        JOptionPane.showMessageDialog(this, mensaje, "AVISO", INFORMATION_MESSAGE);
    }
    private void btnLimpiar_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar_MantenimientoActionPerformed
        // TODO add your handling code here:
        limpiarHabitacion();
    }//GEN-LAST:event_btnLimpiar_MantenimientoActionPerformed

    private void btnDisponibilizar_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisponibilizar_MantenimientoActionPerformed
        // TODO add your handling code here:
        disponibilizarHabitacion();
    }//GEN-LAST:event_btnDisponibilizar_MantenimientoActionPerformed

    private void limpiarHabitacion() {
        HabitacionController habitacionController = new HabitacionController();
        VisitaController visitaController = new VisitaController();
        Integer numHabitacion = Integer.valueOf(txtNumHabitacion_Mantenimiento.getText());

        boolean resultado = habitacionController.limpiarHabitacion(numHabitacion);

        if (!resultado) {
            JOptionPane.showMessageDialog(this, MENSAJE_ERROR_ESTADO_HABITACION, "ERROR", ERROR_MESSAGE);
        } else {
            visitaController.terminarVisita(Integer.parseInt(idVisita_Mantenimiento.getText()));
            JOptionPane.showMessageDialog(this, MENSAJE_EXITO, "AVISO", DEFAULT_OPTION);
        }
    }

    private void disponibilizarHabitacion() {
        HabitacionController habitacionController = new HabitacionController();
        Integer numHabitacion = Integer.valueOf(txtNumHabitacion_Mantenimiento.getText());

        boolean resultado = habitacionController.disponibilizarHabitacion(numHabitacion);

        if (!resultado) {
            JOptionPane.showMessageDialog(this, MENSAJE_ERROR_ESTADO_HABITACION, "ERROR", ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, MENSAJE_EXITO, "AVISO", DEFAULT_OPTION);
        }
    }

    private void btnVer_HabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer_HabitacionActionPerformed
        // TODO add your handling code here:
        HabitacionController habitacionController = new HabitacionController();
        int estado = cboEstado_Habitacion.getSelectedIndex();
        List<Habitacion> habitaciones = habitacionController.listarHabitaciones(estado);

        // Limpiar el modelo de tabla
        tablaHabitaciones.setRowCount(0);

        // Iterar sobre la lista de clientes y agregar cada cliente como una fila en la tabla
        for (Habitacion habitacion : habitaciones) {
            Object[] fila = {
                habitacion.getNroHabitacion(),
                habitacion.getNroCamas(),
                habitacion.getPiso(),
                habitacion.getPrecio(),
                habitacion.getEstado()
            };
            tablaHabitaciones.addRow(fila);
        }

        tbjVer_Habitacion.setModel(tablaHabitaciones);

    }//GEN-LAST:event_btnVer_HabitacionActionPerformed

    private void btnVer_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer_MantenimientoActionPerformed
        // TODO add your handling code here:
        VisitaController visitaController = new VisitaController();
        List<VisitaEnCurso> visitasPorTerminar = visitaController.listarVisitasPorTerminar();

        // Limpiar el modelo de tabla
        tablaMantenimiento.setRowCount(0);

        // Iterar sobre la lista de clientes y agregar cada cliente como una fila en la tabla
        for (VisitaEnCurso visita : visitasPorTerminar) {
            Object[] fila = {
                visita.getId(),
                visita.getNroHabitacion(),
                visita.getEstadoHabitacion(),
                visita.getCliente(),
                visita.getFechaEntrada(),
                visita.getFechaSalida()
            };
            tablaMantenimiento.addRow(fila);
        }

        tbjVer_Mantenimiento.setModel(tablaMantenimiento);
    }//GEN-LAST:event_btnVer_MantenimientoActionPerformed

    private void checkReporteImporteMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkReporteImporteMensualActionPerformed
        // TODO add your handling code here:
        if (checkReporteImporteMensual.isSelected()) {
            checkReporteImporteDiario.setSelected(false);
            checkReporteHabMasUsadas.setSelected(false);
        }
    }//GEN-LAST:event_checkReporteImporteMensualActionPerformed

    private void checkReporteHabMasUsadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkReporteHabMasUsadasActionPerformed
        // TODO add your handling code here:
        if (checkReporteHabMasUsadas.isSelected()) {
            checkReporteImporteDiario.setSelected(false);
            checkReporteImporteMensual.setSelected(false);
        }
    }//GEN-LAST:event_checkReporteHabMasUsadasActionPerformed

    private void checkReporteImporteDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkReporteImporteDiarioActionPerformed
        // TODO add your handling code here:
        if (checkReporteImporteDiario.isSelected()) {
            checkReporteHabMasUsadas.setSelected(false);
            checkReporteImporteMensual.setSelected(false);
        }
    }//GEN-LAST:event_checkReporteImporteDiarioActionPerformed

    private void btnVerReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReporteActionPerformed
        // TODO add your handling code here:        
        VisitaController visitaController = new VisitaController();
        int tipoReporte = 0;
        int mesSeleccionado = cboMes_Reporte.getSelectedIndex();
        Double total = 0.0;

        if (checkReporteHabMasUsadas.isSelected()) {
            tipoReporte = 1;
        } else if (checkReporteImporteDiario.isSelected()) {
            tipoReporte = 2;
        } else if (checkReporteImporteMensual.isSelected()) {
            tipoReporte = 3;
        } else {
            JOptionPane.showMessageDialog(this, MENSAJE_ERROR_FALTA_REPORTE, "AVISO", ERROR_MESSAGE);
            return;
        }

        String resultado = visitaController
                .obtenerReporte(tipoReporte, mesSeleccionado, total);

        txtArea_Reporte.setText(resultado);
    }//GEN-LAST:event_btnVerReporteActionPerformed

    private void btnRegistrar_CienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar_CienteActionPerformed
        // TODO add your handling code here:
        String nroDocCliente, nombreCliente, apellidoCliente, telefonoCliente, correoCliente;
        Integer tipoDocCliente;
        String mensaje;

        tipoDocCliente = cboTipoDocumento_Cliente.getSelectedIndex();
        nroDocCliente = txtNroDocumento_Cliente.getText();
        nombreCliente = txtNombre_Cliente.getText();
        apellidoCliente = txtApellido_Cliente.getText();
        telefonoCliente = txtTelefono_Cliente.getText();
        correoCliente = txtCorreo_Cliente.getText();

        Cliente objCliente = new Cliente(tipoDocCliente,
                nroDocCliente,
                nombreCliente,
                apellidoCliente,
                telefonoCliente,
                correoCliente);

        ClienteController clienteController = new ClienteController();
        mensaje = clienteController.registrarCliente(objCliente);

        JOptionPane.showMessageDialog(this, mensaje, "AVISO", INFORMATION_MESSAGE);
        limpiarClientes();
        cargarCliente();
    }//GEN-LAST:event_btnRegistrar_CienteActionPerformed

    private void cargarCliente() {

        ClienteController clienteController = new ClienteController();
        List<Cliente> clientes = clienteController.listarClientes();

        // Limpiar el modelo de tabla
        tablaClientes.setRowCount(0);

        // Iterar sobre la lista de clientes y agregar cada cliente como una fila en la tabla
        for (Cliente cliente : clientes) {
            Object[] fila = {
                cliente.getId(),
                cliente.getNroDocumento(),
                cliente.getNombre() + " " + cliente.getApellido(),
                cliente.getTelefono(),
                cliente.getCorreo()
            };
            tablaClientes.addRow(fila);
        }

        tbjVer_Cliente.setModel(tablaClientes);
    }

    private void cargarHabitacion() {
        HabitacionController habitacionController = new HabitacionController();
        List<Habitacion> habitaciones = habitacionController.listarHabitaciones(0);

        // Limpiar el modelo de tabla
        tablaHabitaciones.setRowCount(0);

        // Iterar sobre la lista de clientes y agregar cada cliente como una fila en la tabla
        for (Habitacion habitacion : habitaciones) {
            Object[] fila = {
                habitacion.getNroHabitacion(),
                habitacion.getNroCamas(),
                habitacion.getPiso(),
                habitacion.getPrecio(),
                habitacion.getEstado()
            };
            tablaHabitaciones.addRow(fila);
        }

        tbjVer_Habitacion.setModel(tablaHabitaciones);
    }

    private void cargarClienteDeTabla() {

        int fila = tbjVer_Cliente.getSelectedRow();
        String nroDocumento = tbjVer_Cliente.getValueAt(fila, 1).toString();

        ClienteController clienteController = new ClienteController();
        Cliente objCliente = clienteController.buscarCliente(nroDocumento);

        cboTipoDocumento_Cliente.setSelectedIndex(objCliente.getTipoDocumento());
        txtNroDocumento_Cliente.setText(objCliente.getNroDocumento());
        txtNombre_Cliente.setText(objCliente.getNombre());
        txtApellido_Cliente.setText(objCliente.getApellido());
        txtCorreo_Cliente.setText(objCliente.getCorreo());
        txtTelefono_Cliente.setText(objCliente.getTelefono());
        lblId_Cliente.setText(String.valueOf(objCliente.getId()));
    }

    private void cargarHabitacionDeTabla() {

        int fila = tbjVer_Habitacion.getSelectedRow();
        int nroHabitacion = (int) tbjVer_Habitacion.getValueAt(fila, 0);

        HabitacionController habitacionController = new HabitacionController();
        Habitacion objHabitacion = habitacionController.buscarHabitacion(nroHabitacion);

        cboEstado_Habitacion.setSelectedItem(objHabitacion.getEstado());
        txtNum_Habitacion.setText(String.valueOf(objHabitacion.getNroHabitacion()));
        txtNumCamas_Habitacion.setText(String.valueOf(objHabitacion.getNroCamas()));
        txtPiso_Habitacion.setText(String.valueOf(objHabitacion.getPiso()));
        txtPrecio_Habitacion.setText(String.valueOf(objHabitacion.getPrecio()));
    }

    private void cargarMantenimientoDeTabla() {
        int fila = tbjVer_Mantenimiento.getSelectedRow();
        int idVisita = (int) tbjVer_Mantenimiento.getValueAt(fila, 0);
        int nroHabitacion = (int) tbjVer_Mantenimiento.getValueAt(fila, 1);

        idVisita_Mantenimiento.setText(String.valueOf(idVisita));
        txtNumHabitacion_Mantenimiento.setText(String.valueOf(nroHabitacion));
    }

    private void setModeloCliente() {
        String[] cabecera = {"ID", "DOCUMENTO", "CLIENTE", "TELEFONO", "CORREO"};
        tablaClientes.setColumnIdentifiers(cabecera);
        tbjVer_Cliente.setModel(tablaClientes);
    }

    private void setModeloHabitacion() {
        String[] cabecera = {"NRO HAB.", "NRO CAMAS", "PISO", "PRECIO", "ESTADO"};
        tablaHabitaciones.setColumnIdentifiers(cabecera);
        tbjVer_Habitacion.setModel(tablaHabitaciones);
    }

    private void setModeloVisita() {
        String[] cabecera = {"NRO HAB.", "CLIENTE", "FECHA ENTRADA", "FECHA SALIDA"};
        tablaVisitas.setColumnIdentifiers(cabecera);
        tbjVer_Visita.setModel(tablaVisitas);
    }

    private void setModeloMantenimiento() {
        String[] cabecera = {"ID", "NRO HAB.", "ESTADO", "CLIENTE", "FECHA ENTRADA", "FECHA SALIDA"};
        tablaMantenimiento.setColumnIdentifiers(cabecera);
        tbjVer_Mantenimiento.setModel(tablaMantenimiento);
    }

    private void btnActualizar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar_ClienteActionPerformed
        // TODO add your handling code here:
        String nroDocCliente, nombreCliente, apellidoCliente, telefonoCliente, correoCliente;
        Integer tipoDocCliente;
        String mensaje;

        tipoDocCliente = cboTipoDocumento_Cliente.getSelectedIndex();
        nroDocCliente = txtNroDocumento_Cliente.getText();
        nombreCliente = txtNombre_Cliente.getText();
        apellidoCliente = txtApellido_Cliente.getText();
        telefonoCliente = txtTelefono_Cliente.getText();
        correoCliente = txtCorreo_Cliente.getText();

        Cliente objCliente = new Cliente(tipoDocCliente,
                nroDocCliente,
                nombreCliente,
                apellidoCliente,
                telefonoCliente,
                correoCliente);

        objCliente.setId(Integer.valueOf(lblId_Cliente.getText()));

        ClienteController clienteController = new ClienteController();
        mensaje = clienteController.actualizarCliente(objCliente);

        JOptionPane.showMessageDialog(this, mensaje, "AVISO", INFORMATION_MESSAGE);
        limpiarClientes();
        cargarCliente();
    }//GEN-LAST:event_btnActualizar_ClienteActionPerformed

    private void btnVer_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer_ClienteActionPerformed
        // TODO add your handling code here:
        cargarCliente();
    }//GEN-LAST:event_btnVer_ClienteActionPerformed

    private void tbjVer_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbjVer_ClienteMouseClicked
        // TODO add your handling code here:
        cargarClienteDeTabla();
    }//GEN-LAST:event_tbjVer_ClienteMouseClicked

    private void tbjVer_HabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbjVer_HabitacionMouseClicked
        // TODO add your handling code here:
        cargarHabitacionDeTabla();
    }//GEN-LAST:event_tbjVer_HabitacionMouseClicked

    private void btnServicios_HabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicios_HabitacionActionPerformed
        // TODO add your handling code here:
        verServicios();
    }//GEN-LAST:event_btnServicios_HabitacionActionPerformed

    private void btnAlquilar_HabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquilar_HabitacionActionPerformed
        // TODO add your handling code here:
        irRegistrarVisita();
    }//GEN-LAST:event_btnAlquilar_HabitacionActionPerformed

    private void btnValidarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarClienteActionPerformed
        // TODO add your handling code here:
        ClienteController objClienteController = new ClienteController();
        Cliente objCliente = objClienteController.buscarCliente(txtNumDocumentoCliente_Visita.getText());

        if (objCliente == null) {
            JOptionPane.showMessageDialog(this, MENSAJE_CLIENTE_NO_EXISTE, "AVISO", DEFAULT_OPTION);
            btnUsarHabitacion.setEnabled(false);
            jTabbedPane1.setSelectedIndex(2);
        } else {
            JOptionPane.showMessageDialog(this, MENSAJE_EXITO, "AVISO", DEFAULT_OPTION);
            btnUsarHabitacion.setEnabled(true);
        }

    }//GEN-LAST:event_btnValidarClienteActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:.
        btnUsarHabitacion.setEnabled(false);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnVer_VisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer_VisitaActionPerformed
        // TODO add your handling code here:
        VisitaController visitaController = new VisitaController();
        List<VisitaEnCurso> visitaVigente = visitaController.listarVisitasVigentes();

        // Limpiar el modelo de tabla
        tablaVisitas.setRowCount(0);

        // Iterar sobre la lista de clientes y agregar cada cliente como una fila en la tabla
        for (VisitaEnCurso visita : visitaVigente) {
            Object[] fila = {
                visita.getNroHabitacion(),
                visita.getCliente(),
                visita.getFechaEntrada(),
                visita.getFechaSalida()
            };
            tablaVisitas.addRow(fila);
        }

        tbjVer_Visita.setModel(tablaVisitas);
    }//GEN-LAST:event_btnVer_VisitaActionPerformed

    private void tbjVer_VisitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbjVer_VisitaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbjVer_VisitaMouseClicked

    private void tbjVer_MantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbjVer_MantenimientoMouseClicked
        // TODO add your handling code here:
        cargarMantenimientoDeTabla();
    }//GEN-LAST:event_tbjVer_MantenimientoMouseClicked

    private void btnBuscarHab_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHab_MantenimientoActionPerformed
        // TODO add your handling code here:
        VisitaController visitaController = new VisitaController();
        int numHabitacion = Integer.parseInt(txtNumHabitacion_Mantenimiento.getText());
        List<VisitaEnCurso> visitasPorTerminar
                = visitaController.listarVisitasVigentesXNumHabitacion(numHabitacion);

        // Limpiar el modelo de tabla
        tablaMantenimiento.setRowCount(0);

        // Iterar sobre la lista de clientes y agregar cada cliente como una fila en la tabla
        for (VisitaEnCurso visita : visitasPorTerminar) {
            Object[] fila = {
                visita.getId(),
                visita.getNroHabitacion(),
                visita.getEstadoHabitacion(),
                visita.getCliente(),
                visita.getFechaEntrada(),
                visita.getFechaSalida()
            };
            tablaMantenimiento.addRow(fila);
        }

        tbjVer_Mantenimiento.setModel(tablaMantenimiento);
    }//GEN-LAST:event_btnBuscarHab_MantenimientoActionPerformed

    private void irRegistrarVisita() {
        jTabbedPane1.setSelectedIndex(1);
        txtNumHabitacion_Visita.setText(txtNum_Habitacion.getText());
        btnUsarHabitacion.setEnabled(false);
    }

    private void verServicios() {
        Integer numHabitacion = Integer.valueOf(txtNum_Habitacion.getText());
        PopUpServiciosView panel = new PopUpServiciosView(numHabitacion);

        JDialog popup = new JDialog(this, "Mi Popup", true);
        popup.getContentPane().add(panel);
        popup.setSize(680, 300);
        popup.setLocationRelativeTo(this);
        popup.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    private void limpiarClientes() {
        cboTipoDocumento_Cliente.setSelectedIndex(0);
        txtNroDocumento_Cliente.setText(null);
        txtNombre_Cliente.setText(null);
        txtApellido_Cliente.setText(null);
        txtTelefono_Cliente.setText(null);
        txtCorreo_Cliente.setText(null);
    }

    private void limpiarHabitaciones() {
        cboEstado_Habitacion.setSelectedIndex(0);
        txtNum_Habitacion.setText(null);
        txtNumCamas_Habitacion.setText(null);
        txtPiso_Habitacion.setText(null);
        txtPrecio_Habitacion.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar_Cliente;
    private javax.swing.JButton btnActualizar_Habitacion;
    private javax.swing.JButton btnAlquilar_Habitacion;
    private javax.swing.JButton btnBuscarHab_Mantenimiento;
    private javax.swing.JButton btnDisponibilizar_Mantenimiento;
    private javax.swing.JButton btnLimpiar_Mantenimiento;
    private javax.swing.JButton btnRegistrar_Ciente;
    private javax.swing.JButton btnRegistrar_Habitacion;
    private javax.swing.JButton btnServicios_Habitacion;
    private javax.swing.JButton btnUsarHabitacion;
    private javax.swing.JButton btnValidarCliente;
    private javax.swing.JButton btnVerReporte;
    private javax.swing.JButton btnVer_Cliente;
    private javax.swing.JButton btnVer_Habitacion;
    private javax.swing.JButton btnVer_Mantenimiento;
    private javax.swing.JButton btnVer_Visita;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboEstado_Habitacion;
    private javax.swing.JComboBox<String> cboMes_Reporte;
    private javax.swing.JComboBox<String> cboTipoDocumento_Cliente;
    private javax.swing.JRadioButton checkReporteHabMasUsadas;
    private javax.swing.JRadioButton checkReporteImporteDiario;
    private javax.swing.JRadioButton checkReporteImporteMensual;
    private javax.swing.JLabel idVisita_Mantenimiento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelHabitaciones;
    private javax.swing.JPanel jPanelMantenimiento;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JPanel jPanelReportes;
    private javax.swing.JScrollPane jScrollPane_Cliente;
    private javax.swing.JScrollPane jScrollPane_Habitacion;
    private javax.swing.JScrollPane jScrollPane_Mantenimiento;
    private javax.swing.JScrollPane jScrollPane_Reporte;
    private javax.swing.JScrollPane jScrollPane_Visita;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblId_Cliente;
    private javax.swing.JTable tbjVer_Cliente;
    private javax.swing.JTable tbjVer_Habitacion;
    private javax.swing.JTable tbjVer_Mantenimiento;
    private javax.swing.JTable tbjVer_Visita;
    private javax.swing.JTextField txtApellido_Cliente;
    private javax.swing.JTextArea txtArea_Reporte;
    private javax.swing.JTextField txtCorreo_Cliente;
    private javax.swing.JTextField txtNombre_Cliente;
    private javax.swing.JTextField txtNroDocumento_Cliente;
    private javax.swing.JTextField txtNumCamas_Habitacion;
    private javax.swing.JTextField txtNumDocumentoCliente_Visita;
    private javax.swing.JTextField txtNumHabitacion_Mantenimiento;
    private javax.swing.JTextField txtNumHabitacion_Visita;
    private javax.swing.JTextField txtNum_Habitacion;
    private javax.swing.JTextField txtPiso_Habitacion;
    private javax.swing.JTextField txtPrecio_Habitacion;
    private javax.swing.JTextField txtTelefono_Cliente;
    // End of variables declaration//GEN-END:variables
}
